"""Initial migration

Revision ID: 8af8b2a63185
Revises: 6724a7bdebab
Create Date: 2024-03-05 17:21:57.909750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af8b2a63185'
down_revision: Union[str, None] = '6724a7bdebab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_news_id'), 'google_news', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_news_id'), table_name='google_news')
    op.drop_table('google_news')
    # ### end Alembic commands ###
