"""Create news table

Revision ID: c31acb85fec3
Revises: 4ef04bf775f9
Create Date: 2024-02-29 17:47:16.656067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31acb85fec3'
down_revision: Union[str, None] = '4ef04bf775f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_news', sa.Column('source', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_news', 'source')
    # ### end Alembic commands ###
